version: "2.1"

services:
  localstack_main:
    container_name: localstack_main
    hostname: localstack_main
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LAMBDA_DOCKER_NETWORK=localstackreverseproxy_lntk
      - AWS_CA_BUNDLE=/var/task/myCA.pem
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - lntk
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/certs
    networks:
      lntk:
        aliases:
          - s3.amazonaws.com
          - sts.amazonaws.com
          - dynamodb.us-east-1.amazonaws.com
          - sns.us-east-1.amazonaws.com
          - ssm.us-east-1.amazonaws.com
          - states.us-east-1.amazonaws.com
          - mybucket.s3.amazonaws.com

networks:
  lntk:
    driver: bridge
